name: Deploy HathorDice dApp
description: Build and deploy the HathorDice dApp to AWS S3/CloudFront

inputs:
  site:
    description: The site name to build and deploy (staging, production)
    required: true
  aws-region:
    description: The AWS region to deploy to
    required: true
    default: us-east-1
  aws-role:
    description: The AWS IAM role to assume for deployment
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      # https://github.com/aws-actions/configure-aws-credentials/releases/tag/v5.1.1
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role }}

    - name: Set up Node.js 24.x
      # https://github.com/actions/setup-node/releases/tag/v6.1.0
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
      with:
        node-version: 24.x

    - name: Download node modules
      # https://github.com/actions/download-artifact/releases/tag/v6.0.0
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
      with:
        name: node_modules

    - name: Build
      shell: bash
      run: |
        tar -xf node_modules.tar
        make build site=${{ inputs.site }}

    - name: Deploy
      shell: bash
      run: |
        make sync site=${{ inputs.site }}
        make clear_cloudfront_cache site=${{ inputs.site }}
